# Generated by Django 3.0.8 on 2020-07-27 23:52

from django.db import migrations

from blog.models import GradeModel


def add_grade(apps, schema_editor):
    Grade = apps.get_model('blog', GradeModel.__name__)
    normal = Grade(id=1, name="normal")
    normal.save()
    silver = Grade(id=2, name="silver")
    silver.save()
    gold = Grade(id=3, name="gold")
    gold.save()


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_grade)
    ]
