version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog

  python:
    build: ./python
    volumes:
      - ../../code:/code
    depends_on:
      - db
    tty: true
