version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: blog

  python:
    build: ./python
    volumes:
      - ../../code:/code
    # sh command of last line is required prevent this container from exit when command finished.
    command: >
      sh -c '
      pipenv install --system --ignore-pipfile --deploy &&
      python manage.py migrate &&
      sh
      '
    depends_on:
      - db
